import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

const interFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${interFont.className} antialiased dark px-6 sm:px-0`}>
				{children}
			</body>
		</html>
	);
}
